version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: transcript_server
    ports:
      - "4001:4001"

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: transcript_client
    depends_on:
      - server

